pattern_list = {
"CDL2CROWS":"Two Crows",
"CDL3BLACKCROWS":"Three Black Crows",
"CDL3INSIDE":"Three Inside Up/Down",
"CDL3LINESTRIKE":"Three-Line Strike",
"CDL3OUTSIDE":"Three Outside Up/Down",
"CDL3STARSINSOUTH":"Three Stars In The South",
"CDL3WHITESOLDIERS":"Three Advancing White Soldiers",
"CDLABANDONEDBABY":"Abandoned Baby",
"CDLADVANCEBLOCK":"Advance Block",
"CDLBELTHOLD":"Belt-hold",
"CDLBREAKAWAY":"Breakaway",
"CDLCLOSINGMARUBOZU":"Closing Marubozu",
"CDLCONCEALBABYSWALL":"Concealing Baby Swallow",
"CDLCOUNTERATTACK":"Counterattack",
"CDLDARKCLOUDCOVER":"Dark Cloud Cover",
"CDLDOJI":"Doji",
"CDLDOJISTAR":"Doji Star",
"CDLDRAGONFLYDOJI":"Dragonfly Doji",
"CDLENGULFING":"Engulfing Pattern",
"CDLEVENINGDOJISTAR":"Evening Doji Star",
"CDLEVENINGSTAR":"Evening Star",
"CDLGAPSIDESIDEWHITE":"Up/Down-gap side-by-side white lines",
"CDLGRAVESTONEDOJI":"Gravestone Doji",
"CDLHAMMER":"Hammer",
"CDLHANGINGMAN":"Hanging Man",
"CDLHARAMI":"Harami Pattern",
"CDLHARAMICROSS":"Harami Cross Pattern",
"CDLHIGHWAVE":"High-Wave Candle",
"CDLHIKKAKE":"Hikkake Pattern",
"CDLHIKKAKEMOD":"Modified Hikkake Pattern",
"CDLHOMINGPIGEON":"Homing Pigeon",
"CDLIDENTICAL3CROWS":"Identical Three Crows",
"CDLINNECK":"In-Neck Pattern",
"CDLINVERTEDHAMMER":"Inverted Hammer",
"CDLKICKING":"Kicking",
"CDLKICKINGBYLENGTH":"Kicking - bull/bear determined by the longer marubozu",
"CDLLADDERBOTTOM":"Ladder Bottom",
"CDLLONGLEGGEDDOJI":"Long Legged Doji",
"CDLLONGLINE":"Long Line Candle",
"CDLMARUBOZU":"Marubozu",
"CDLMATCHINGLOW":"Matching Low",
"CDLMATHOLD":"Mat Hold",
"CDLMORNINGDOJISTAR":"Morning Doji Star",
"CDLMORNINGSTAR":"Morning Star",
"CDLONNECK":"On-Neck Pattern",
"CDLPIERCING":"Piercing Pattern",
"CDLRICKSHAWMAN":"Rickshaw Man",
"CDLRISEFALL3METHODS":"Rising/Falling Three Methods",
"CDLSEPARATINGLINES":"Separating Lines",
"CDLSHOOTINGSTAR":"Shooting Star",
"CDLSHORTLINE":"Short Line Candle",
"CDLSPINNINGTOP":"Spinning Top",
"CDLSTALLEDPATTERN":"Stalled Pattern",
"CDLSTICKSANDWICH":"Stick Sandwich",
"CDLTAKURI":"Takuri (Dragonfly Doji with very long lower shadow)",
"CDLTASUKIGAP":"Tasuki Gap",
"CDLTHRUSTING":"Thrusting Pattern",
"CDLTRISTAR":"Tristar Pattern",
"CDLUNIQUE3RIVER":"Unique 3 River",
"CDLUPSIDEGAP2CROWS":"Upside Gap Two Crows",
"CDLXSIDEGAP3METHODS":"Upside/Downside Gap Three Methods",
}

pattern_img = {
"CDL2CROWS":["http://static.incrediblecharts.com/images/candlestick-patterns/twocrows-minus.svg", 'up trend', '', 'consolidation'],
"CDL3BLACKCROWS":["http://static.incrediblecharts.com/images/candlestick-patterns/threeblackcrows-minus.svg", "bearish", "strong", "reversal"],
"CDL3INSIDE":["http://static.incrediblecharts.com/images/candlestick-patterns/threeinsideup-plus.svg", "bullish/bearish", "weak", "reversal"],
"CDL3LINESTRIKE":[ "http://static.incrediblecharts.com/images/candlestick-patterns/threelinestrike-minus.svg", "bullish/bearish", "reliable/strong", "reversal"],
"CDL3OUTSIDE":["http://static.incrediblecharts.com/images/candlestick-patterns/threeoutsideup-plus.svg" , "bullish/bearsih", "reliable", "reversal"],
"CDL3STARSINSOUTH":["http://static.incrediblecharts.com/images/candlestick-patterns/threestarsinthesouth-plus.svg", "down trend", "rare", "consolidation"],
"CDL3WHITESOLDIERS":["http://static.incrediblecharts.com/images/candlestick-patterns/threewhitesoldiers-plus.svg", "bullish", "strong", "reversal"],
"CDLABANDONEDBABY":["http://static.incrediblecharts.com/images/candlestick-patterns/abandonedbaby-plus.svg", 'bullish/bearish', 'reliable', 'reversal'],
"CDLADVANCEBLOCK":["http://static.incrediblecharts.com/images/candlestick-patterns/advanceblock-minus.svg", 'bullish', 'weak', 'continuation'],
"CDLBELTHOLD":["http://static.incrediblecharts.com/images/candlestick-patterns/belthold-plus.svg", 'bullish/bearish', 'reliable', 'reversal'],
"CDLBREAKAWAY":["http://static.incrediblecharts.com/images/candlestick-patterns/breakaway-plus.svg", 'bullish/bearish', 'weak', 'reversal'],
"CDLCLOSINGMARUBOZU":["Closing Marubozu"],
"CDLCONCEALBABYSWALL":["http://static.incrediblecharts.com/images/candlestick-patterns/concealing-babyswallow-plus.svg", 'bearlish','strong','continuation'],
"CDLCOUNTERATTACK":["Counterattack"],
"CDLDARKCLOUDCOVER":["http://static.incrediblecharts.com/images/candlestick-patterns/darkcloudcover-minus.svg", 'bearish','weak','reversal'],
"CDLDOJI":["Doji"],
"CDLDOJISTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/dojistar-minus.svg",'bullish/bearish', 'continuation', 'reliable'],
"CDLDRAGONFLYDOJI":["http://static.incrediblecharts.com/images/candlestick-patterns/dragonfly-minus.svg", 'up trend', '', 'consolidation'],
"CDLENGULFING":["http://static.incrediblecharts.com/images/candlestick-patterns/engulfing-plus.svg", 'bullish/bearish', 'reliable', 'reversal'],
"CDLEVENINGDOJISTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/eveningdojistar-minus.svg", 'bearish', 'reliable', 'reversal'],
"CDLEVENINGSTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/eveningstar-minus.svg", 'bearish','strong','reversal'],
"CDLGAPSIDESIDEWHITE": ["http://static.incrediblecharts.com/images/candlestick-patterns/sidebysidewhitelines-plus.svg", 'bullish/bearsih', 'weak', 'continuation'],
"CDLGRAVESTONEDOJI":["http://static.incrediblecharts.com/images/candlestick-patterns/gravestone-plus.svg", 'down trend', '', 'consolidation'],
"CDLHAMMER":["http://static.incrediblecharts.com/images/candlestick-patterns/hammer-plus.svg", 'bullish', 'weak', 'reversal'],
"CDLHANGINGMAN":["http://static.incrediblecharts.com/images/candlestick-patterns/hangingman.svg", 'bullish', 'weak', 'continuation'],
"CDLHARAMI":["http://static.incrediblecharts.com/images/candlestick-patterns/harami-minus.svg", 'up/down trend', '', 'consolidation'],
"CDLHARAMICROSS":["http://static.incrediblecharts.com/images/candlestick-patterns/haramicross-minus.svg", 'up/down trend', '', 'consolidation'],
"CDLHIGHWAVE":["High-Wave Candle"],
"CDLHIKKAKE":["Hikkake Pattern"],
"CDLHIKKAKEMOD":["Modified Hikkake Pattern"],
"CDLHOMINGPIGEON":["http://static.incrediblecharts.com/images/candlestick-patterns/homingpigeon-plus.svg", 'down trend', '', 'consolidation'],
"CDLIDENTICAL3CROWS":["http://static.incrediblecharts.com/images/candlestick-patterns/identicalthreecrows-minus.svg", 'bearish', 'strong' ,'reversal' ],
"CDLINNECK":["http://static.incrediblecharts.com/images/candlestick-patterns/inneckline-plus.svg", 'up trend', '', 'consolidation'],
"CDLINVERTEDHAMMER":["http://static.incrediblecharts.com/images/candlestick-patterns/invertedhammer.svg"],
"CDLKICKING":['http://static.incrediblecharts.com/images/candlestick-patterns/kicking-minus.svg', 'up trend', '','consolidation'],
"CDLKICKINGBYLENGTH":["Kicking - bull/bear determined by the longer marubozu"],
"CDLLADDERBOTTOM":["http://static.incrediblecharts.com/images/candlestick-patterns/ladderbottom-plus.svg", 'down trend', '','consolidation'],
"CDLLONGLEGGEDDOJI":["Long Legged Doji"],
"CDLLONGLINE":["Long Line Candle"],
"CDLMARUBOZU":["Marubozu"],
"CDLMATCHINGLOW":["http://static.incrediblecharts.com/images/candlestick-patterns/matchinglow-plus.svg", 'bearish', 'weak', 'continuation'],
"CDLMATHOLD":["Mat Hold"],
"CDLMORNINGDOJISTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/morningdojistar-plus.svg", 'bullish', 'reliable', 'reversal'],
"CDLMORNINGSTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/morningstar-plus.svg", 'bullish', 'strong', 'reversal'],
"CDLONNECK":["http://static.incrediblecharts.com/images/candlestick-patterns/onneckline-plus.svg", 'up trend', '', 'consolidation'],
"CDLPIERCING":["http://static.incrediblecharts.com/images/candlestick-patterns/piercingline-plus.svg", 'bullish', 'weak','reversal'],
"CDLRICKSHAWMAN":["Rickshaw Man"],
"CDLRISEFALL3METHODS":["http://static.incrediblecharts.com/images/candlestick-patterns/risingthreemethods-plus.svg", 'bullish/bearish', 'reliable', 'continuation'],
"CDLSEPARATINGLINES":["http://static.incrediblecharts.com/images/candlestick-patterns/separatinglines-plus.svg", 'bullish/bearish', 'reliable','continuation'],
"CDLSHOOTINGSTAR":["http://static.incrediblecharts.com/images/candlestick-patterns/shootingstar-minus.svg", 'bearish', 'weak','reversal'],
"CDLSHORTLINE":["Short Line Candle"],
"CDLSPINNINGTOP":["Spinning Top"],
"CDLSTALLEDPATTERN":["Stalled Pattern"],
"CDLSTICKSANDWICH":["http://static.incrediblecharts.com/images/candlestick-patterns/sticksandwich-plus.svg", 'bearish', 'weak', 'continuation'],
"CDLTAKURI":"Takuri (Dragonfly Doji with very long lower shadow)",
"CDLTASUKIGAP":["http://static.incrediblecharts.com/images/candlestick-patterns/upsidetasukigap-plus.svg", 'up trend', '', 'consolidation'],
"CDLTHRUSTING":["Thrusting Pattern"],
"CDLTRISTAR":["Tristar Pattern"],
"CDLUNIQUE3RIVER":["http://static.incrediblecharts.com/images/candlestick-patterns/unique-threeriver.svg", 'bearish', 'weak', 'continuation'],
"CDLUPSIDEGAP2CROWS":["http://static.incrediblecharts.com/images/candlestick-patterns/upsidegap-twocrows-minus.svg", 'bullish', 'weak','continuation'],
"CDLXSIDEGAP3METHODS":["http://static.incrediblecharts.com/images/candlestick-patterns/downsidegap-threemethods-minus.svg", 'bullish/bearish', 'weak', 'reversal'],
}
